language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION < '3.0' ]]; then pip install --use-mirrors unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION >= '3.0' ]]; then pip install --use-mirrors unittest2py3k; fi
  - pip install -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 rtkit
  - pyflakes -x W rtkit
  - py.test --doctest-modules rtkit -v