# https://travis-ci.org/#!/z4r/python-rtkit
language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION < '2.7' ]]; then pip install --use-mirrors unittest2; fi
  - pip install -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 rtkit
  - py.test --doctest-modules rtkit -v